# Generated by Django 4.0 on 2021-12-13 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predDash', '0004_alter_analysisdeets_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisdeets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
